CREATE TABLE IF NOT EXISTS `Scream` (
	`ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`DateCreated` DATETIME NOT NULL,
	`DateEdited` DATETIME NULL,
	`Body` NVARCHAR(512) NOT NULL,
	`UserID` INT NOT NULL,
	`ParentID` INT UNSIGNED NOT NULL DEFAULT 0,
	`ReplyToID` INT UNSIGNED NOT NULL DEFAULT 0,
	`SourceAppID` INT UNSIGNED NOT NULL DEFAULT 0,
	`TotalViews` INT UNSIGNED NOT NULL DEFAULT 0,
	PRIMARY KEY (`ID`),
	CONSTRAINT `FK_ScreamUser` FOREIGN KEY (`UserID`) REFERENCES `User` (`ID`) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `ScreamHistory` (
	`ScreamID` INT UNSIGNED NOT NULL,
	`DateCreated` DATETIME NOT NULL,
	`DateEdited` DATETIME NULL,
	`DateRecorded` DATETIME NOT NULL,
	`Body` NVARCHAR(512) NOT NULL,
	`UserID` INT NOT NULL,
	`ParentID` INT UNSIGNED NOT NULL,
	`ReplyToID` INT UNSIGNED NOT NULL,
	`SourceAppID` INT UNSIGNED NOT NULL,
	`TotalViews` INT UNSIGNED NOT NULL
);
